batch_size: 16
distributed: False
num_epochs: 3
accum_iter: 10
base_lr: 1.0
max_padding: 72
warmup: 3000
device: "cpu"
data_slice: "4%"

file_prefix: "wmt16_model_"
model_path: "wmt16_model_final.pt"
run: "tests"
project: "transformer"
run_id: "70b7c4f6"

model:
  n: 6
  d_model: 512
  d__ff: 2048
  h: 8
  dropout: 0.1
